name: 11nuk5 0.0.11

on:
  workflow_dispatch:

jobs:
  run-11nuk5:
    runs-on: ubuntu-latest

    steps:
        
      - name: Run container
        run: |
          docker run -d \
          --name=11nuk5 \
          --cap-add=NET_ADMIN \
          --privileged \
          --security-opt seccomp=unconfined `#optional` \
          --device=/dev/kvm \
          --device=/dev/net/tun \
          -e TZ=Etc/UTC \
          -e QEMUDISPLAY=web \
          -p 8006:8006 \
          -v /config:/storage \
          --shm-size="1gb" \
          --restart unless-stopped \
          r014nd5m1th/11nuk5
          
      - name: Show running containers
        run: docker ps
        
      - name: Run Fl4r3d
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:8006

      - name: Keep alive for 5 hours
        run: sleep 18000
